-- DROP TABLE users;

CREATE TABLE users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_profile_id int8 NULL,
	username varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_user_profile_id_key UNIQUE (user_profile_id),
	CONSTRAINT users_username_key UNIQUE (username),
	CONSTRAINT user_profile_fk FOREIGN KEY (user_profile_id) REFERENCES user_profiles(id)
);